version: '3'

services:

    blockchain-okd-service:
      environment:
        PORT: 8100
        POSTGRES_HOST: postgres-image
      env_file:
        - docker-compose.env
      depends_on:
        - postgres-image
      ports:
        - "8100:8100"
      build:
        context: ./
        dockerfile: ./Dockerfile
      image: blockchain-okd-image:latest
      restart: on-failure
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s


    postgres-image:
      image: postgres:14.4-alpine3.16
      env_file:
        - docker-compose.env
      volumes:
        - ./pgdata:/var/lib/postgresql/data
